DROP TABLE IF EXISTS "CONCEPT";
CREATE TABLE "CONCEPT" ("ID" INTEGER PRIMARY KEY  AUTOINCREMENT , "CODE" VARCHAR UNIQUE , "VALUE" VARCHAR, "CLASS" VARCHAR);
INSERT INTO "CONCEPT" VALUES(1,'M','Male','sex');
INSERT INTO "CONCEPT" VALUES(2,'F','Female','sex');
INSERT INTO "CONCEPT" VALUES(3,'U','Unknown','sex');
INSERT INTO "CONCEPT" VALUES(4,'mr','Mr.','prefix');
INSERT INTO "CONCEPT" VALUES(5,'ms','Ms.','prefix');
INSERT INTO "CONCEPT" VALUES(6,'mrs','Mrs.','prefix');
INSERT INTO "CONCEPT" VALUES(7,'dr','Dr.','prefix');
INSERT INTO "CONCEPT" VALUES(8,'AP','Andhra Pradesh','state');
INSERT INTO "CONCEPT" VALUES(9,'DL','New Delhi','state');
INSERT INTO "CONCEPT" VALUES(10,'KA','Karnataka','state');
INSERT INTO "CONCEPT" VALUES(11,'KL','Kerala','state');
INSERT INTO "CONCEPT" VALUES(12,'PB','Punjab','state');
INSERT INTO "CONCEPT" VALUES(13,'NY','New York','state');
INSERT INTO "CONCEPT" VALUES(14,'NJ','New Jersey','state');
INSERT INTO "CONCEPT" VALUES(15,'MX','Mexico','state');
INSERT INTO "CONCEPT" VALUES(16,'CA','California','state');
INSERT INTO "CONCEPT" VALUES(17,'FL','Florida','state');
INSERT INTO "CONCEPT" VALUES(18,'AD','Abu Dhabi','state');
INSERT INTO "CONCEPT" VALUES(19,'SJ','Sharjah','state');
INSERT INTO "CONCEPT" VALUES(20,'BG','Bangalore','city');
INSERT INTO "CONCEPT" VALUES(21,'MY','Mysore','city');
INSERT INTO "CONCEPT" VALUES(22,'HYD','Hyderabad','city');
INSERT INTO "CONCEPT" VALUES(23,'ALB','Alabama','city');
INSERT INTO "CONCEPT" VALUES(24,'BST','Boston','city');
INSERT INTO "CONCEPT" VALUES(25,'ATL','Atlantic City','city');
INSERT INTO "CONCEPT" VALUES(26,'PR','Princeton','city');
INSERT INTO "CONCEPT" VALUES(27,'ARZ','Arizona','city');
INSERT INTO "CONCEPT" VALUES(28,'GA','Georgia','city');
INSERT INTO "CONCEPT" VALUES(30,'IN','Indiana','city');
INSERT INTO "CONCEPT" VALUES(31,'WH','Washington','city');
INSERT INTO "CONCEPT" VALUES(32,'DU','Dubai','city');
INSERT INTO "CONCEPT" VALUES(33,'ABU','Abu Dhabi','city');
INSERT INTO "CONCEPT" VALUES(34,'SH','Sharjah','city');
INSERT INTO "CONCEPT" VALUES(35,'MUS','Muscut','city');
INSERT INTO "CONCEPT" VALUES(36,'QU','Qutar','city');
INSERT INTO "CONCEPT" VALUES(37,'AH','Ahmedabad','city');
INSERT INTO "CONCEPT" VALUES(38,'CH','Chennai','city');
INSERT INTO "CONCEPT" VALUES(39,'KAN','Kanpur','city');
INSERT INTO "CONCEPT" VALUES(40,'KOL','Kolkata','city');
INSERT INTO "CONCEPT" VALUES(41,'MUM','Mumbai','city');
INSERT INTO "CONCEPT" VALUES(42,'SUR','Surat','city');
INSERT INTO "CONCEPT" VALUES(43,'PUNE','Pune','city');
INSERT INTO "CONCEPT" VALUES(44,'BP','Blood Pressure','illness');
INSERT INTO "CONCEPT" VALUES(45,'THY','Thyroid','illness');
INSERT INTO "CONCEPT" VALUES(46,'DIA','Diabetes','illness');
INSERT INTO "CONCEPT" VALUES(47,'JP','Join Pains','illness');
INSERT INTO "CONCEPT" VALUES(48,'MG','Migraine','illness');
INSERT INTO "CONCEPT" VALUES(52,'MR','Married','maritalStatus');
INSERT INTO "CONCEPT" VALUES(53,'S','Single','maritalStatus');
INSERT INTO "CONCEPT" VALUES(54,'VI','Visual impairment','disability');
INSERT INTO "CONCEPT" VALUES(55,'HI','Hearing impairment','disability');
INSERT INTO "CONCEPT" VALUES(56,'PD','Physical disability','disability');
INSERT INTO "CONCEPT" VALUES(57,'MH','Mental health and emotional disabilities','disability');
INSERT INTO "CONCEPT" VALUES(58,'CN','Chinese','ethnicGroup');
INSERT INTO "CONCEPT" VALUES(59,'AM','American','ethnicGroup');
INSERT INTO "CONCEPT" VALUES(60,'AR','Arab','ethnicGroup');
INSERT INTO "CONCEPT" VALUES(61,'ID','Indian','ethnicGroup');
INSERT INTO "CONCEPT" VALUES(62,'JN','Japanese','ethnicGroup');
INSERT INTO "CONCEPT" VALUES(63,'CHR','Christian','religion');
INSERT INTO "CONCEPT" VALUES(64,'HD','Hindu','religion');
INSERT INTO "CONCEPT" VALUES(65,'MSL','Musilim','religion');
INSERT INTO "CONCEPT" VALUES(66,'ARY','Aryan','race');
INSERT INTO "CONCEPT" VALUES(67,'SEM','Semitic','race');
INSERT INTO "CONCEPT" VALUES(68,'HMT','Hamitic','race');
INSERT INTO "CONCEPT" VALUES(69,'DRV','Dravidians','race');
INSERT INTO "CONCEPT" VALUES(70,'DN','None','disability');
INSERT INTO "CONCEPT" VALUES(71,'IND','India','country');
INSERT INTO "CONCEPT" VALUES(72,'USA','United States of America','country');
INSERT INTO "CONCEPT" VALUES(73,'UAE','United Arab Emirates','country');
