/**
 * 
 */
package com.hin.hl7messaging.config;

/**
 * @author salam.halley
 *
 */
public enum HINConfigurationProperty {
 
	MESSAGE_REPOSITORY_CONNECTION_PROPERTIES("MESSAGE_REPOSITORY_CONNECTION_PROPERTIES"),
	SERVICE_LAYER_IMPLEMENTATION("SERVICE_LAYER_IMPLEMENTATION"),
	REPOSITORY_LAYER_IMPLEMENTATION("SERVICE_LAYER_IMPLEMENTATION"), 
	REPOSITORY_INJECTION_METHOD("REPOSITORY_INJECTION_METHOD"), 
	CASSANDRA_CLIENT_INJECTION_METHOD("CASSANDRA_CLIENT_INJECTION_METHOD"), 
	SERVICE_LAYER_BEAN("SERVICE_LAYER_BEAN"), 
	REPOSITORY_LAYER_BEAN("REPOSITORY_LAYER_BEAN"), 
	CASSANDRA_CLIENT_BEAN("CASSANDRA_CLIENT_BEAN"),
	CASSANDRA_CLIENT_IMPLEMENTATION("CASSANDRA_CLIENT_IMPLEMENTATION"), 
	CASSANDRA_CLIENT_INIT_METHOD("CASSANDRA_CLIENT_INIT_METHOD"), 
	CASSANDRA_CLIENT_SELECT_KEYSPACE_METHOD("CASSANDRA_CLIENT_SELECT_KEYSPACE_METHOD"), 
	
	// has to be removed once the MessageRepository is up
	REPOSITORY_STANDARD_LAYER_IMPLEMENTATION("REPOSITORY_STANDARD_LAYER_IMPLEMENTATION"), 
	REPOSITORY_STANDARD_LAYER_BEAN("REPOSITORY_STANDARD_LAYER_BEAN"), 
	CASSANDRA_CLIENT_BEAN_FOR_STANDARD("CASSANDRA_CLIENT_BEAN_FOR_STANDARD"), 
	WORKFLOW_DEPLOYMENT_PATH("WORKFLOW_DEPLOYMENT_PATH"),
	ACCOUNT_ACTIVATION_URL("ACCOUNT_ACTIVATION_URL"),
	HIS_LOOKUP_SERVICE("HIS_LOOKUP_SERVICE"),
	WORKFLOW_CONFIG_PATH("WORKFLOW_CONFIG_PATH"),
	PROCESS_CONFIG_PATH("PROCESS_CONFIG_PATH"),
	CONTEXT_PATH("CONTEXT_PATH"), WORKFLOW_MANAGER_BEAN("WORKFLOW_MANAGER_BEAN"), 
	MESSAGE_DEFAULT_IMAGE_PATH("MESSAGE_DEFAULT_IMAGE_PATH"), 
	CALENDAR_EVENT_READ_XPATH("CALENDAR_EVENT_READ_XPATH"), 
	CALENDAR_EVENT_ARTIFACT("CALENDAR_EVENT_ARTIFACT"),	
	MESSAGE_POST_SERVER_URL("MESSAGE_POST_SERVER_URL"), 
	DEPLOY_WORKFLOW("DEPLOY_WORKFLOW"),
	MESSAGE_ARCHIVE_CONFIGURATION_PATH("MESSAGE_ARCHIVE_CONFIGURATION_PATH"),
	
	//Lucene index dir path
	LUCENE_INDEX_DIR_PATH("LUCENE_INDEX_DIR_PATH");
	
	String propertyName;
	
	private HINConfigurationProperty(String propertyName){
		this.propertyName = propertyName;
	}

	public String getPropertyName() {
		return propertyName;
	}

	public void setPropertyName(String propertyName) {
		this.propertyName = propertyName;
	}		
}
